[package]
name = "tstit"
description = "Test It. REST It."
version = "0.2.0"
edition = "2024"

[dependencies]
argh = "0.1"
toml = "0.8"
pretty_env_logger = "0.5"
log = "0.4"
serde = { version="1.0", features=['derive'] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "2.0"
regex = "1.11"
